replicaCount: 1

image:
  repository: accounting
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables for the application
env:
  APP_PORT: 8080
  APP_HOST: localhost
  APP_DB_PATH: accounting.db
  APP_SHUTDOWN_TIMEOUT: 10
  APP_REQUESTS_PER_SECOND: 100
  APP_BURST_SIZE: 200
  APP_USERS: "admin:admin123,user:user123" 